Ensure teams is available with 1.1. SAML name

diff --git a/ansible-env b/ansible-env
--- a/ansible-env
+++ b/ansible-env
@@ -25,7 +25,12 @@ rm -rf "$KEYSTORE_DIR/*"
 if [ "$1" == 'vm' ]; then
   # we can read the gpg passphrase from the file
   gpg --batch --quiet --passphrase-file gpg/passphrase.txt --decrypt "gpg/tarred_and_crypted_keystores/$1.tar.gpg" | tar -x -C "$KEYSTORE_DIR"
-  #no need to provide the username when targeting vagrant: it's always the same.
+  if ([ ! -f "$KEYSTORE_DIR/meta" ] || [ ! -f "$KEYSTORE_DIR/1" ]);
+    then
+      echo "GPG decryption failed! Did you import gpg/vm.key into your GPG Keychain?"
+      exit 1
+  fi
+  # no need to provide the username when targeting vagrant: it's always the same.
   ansible-playbook -i "inventory/$1" --private-key `pwd`/.vagrant/machines/openconext-vm/virtualbox/private_key  -u vagrant "$2"
 else
   gpg --batch --quiet --decrypt "gpg/tarred_and_crypted_keystores/$1.tar.gpg" | tar -x -C "$KEYSTORE_DIR"
