Update hapos-update to upstream 0.4 which has merged our local changes.

diff --git a/roles/haproxy/files/hapos-upd b/roles/haproxy/files/hapos-upd
--- a/roles/haproxy/files/hapos-upd
+++ b/roles/haproxy/files/hapos-upd
@@ -7,7 +7,7 @@
 
 set -o nounset
 
-VERSION="0.3.0"
+VERSION="0.4.0"
 
 PROGNAME="hapos-upd"
 
@@ -155,6 +155,8 @@ Options:
                          that don't include the signer certificate).
 
       --noverify       : Do not verify OCSP response.
+
+ -S, --skip-update     : Do not notify haproxy of the new OCSP response.
 
  -h, --help            : this help."
 }
@@ -418,8 +420,7 @@ else
 fi
 
 # check if the EE certificate validates against the chain
-# THKI: disabled because our chain doesn't contain the self-signed CA, so fails
-true || $OPENSSL_BIN verify -CAfile $TMP/chain.pem $TMP/ee.pem &>>$TMP/log
+$OPENSSL_BIN verify -CAfile $TMP/chain.pem $TMP/ee.pem &>>$TMP/log
 
 if [ $? -ne 0 ]; then
     if [ -e $CERT.issuer ]; then
@@ -516,18 +517,28 @@ if [ $DEBUG -eq 0 ]; then
 
     if [ $SKIP_UPDATE -eq 0 ]; then
         if [ $ISNEW -eq 1 ]; then
+            # no .ocsp file found, maybe it's an initial run
+            Debug "Reloading haproxy."
+
             service haproxy reload
+
+            if [ $? -ne 0 ]; then
+                Error 5 "can't reload haproxy with 'service haproxy reload'"
+            fi
         else
-        # update haproxy via local UNIX socket
+            # update haproxy via local UNIX socket
+            Debug "Updating haproxy."
+
             echo "set ssl ocsp-response `base64 -w 0 $TMP/ocsp.der`" | $SOCAT_BIN stdio $HAPROXY_ADMIN_SOCKET &>>$TMP/log
+
+            if [ $? -ne 0 ]; then
+                Error 5 "can't update haproxy ssl ocsp-response using $HAPROXY_ADMIN_SOCKET socket"
+            fi
         fi
     else
         Debug "Not notifying haproxy because skip-update is set."
     fi
 
-    if [ $? -ne 0 ]; then
-        Error 5 "can't update haproxy ssl ocsp-response using $HAPROXY_ADMIN_SOCKET socket"
-    fi
 else
     Debug "Debug mode: haproxy update skipped."
 fi
