#30 add env and domain as parameters

diff --git a/scripts/generate-new-passwords b/scripts/generate-new-passwords
--- a/scripts/generate-new-passwords
+++ b/scripts/generate-new-passwords
@@ -12,24 +12,36 @@ SECRET_VARS_FILE=../secrets/secret-vars.yml
 SECRET_VARS_TEMPLATE_FILE=../templates/secret-vars-template.yml
 # ----- End configuration
 
+BASEDIR=$(dirname $0)
+BASENAME=$(basename $0)
+
 # ----- Input handling
-if [ $# -eq 0 ]
+if [ $# -lt 2 ]
   then
-    echo "INFO: No arguments supplied, using default file location" $SECRET_VARS_FILE
+    echo "INFO: No arguments supplied, syntax: $BASENAME environment domain [secret-vars-file]"
+    exit 1
 fi
 
-if [ $# -gt 1 ]
+if [ $# -eq 2 ]
   then
-    echo "ERROR: Only 1 argument expected please supply only the file containing the secrets, for example " $SECRET_VARS_FILE
+    echo "INFO: No secret file supplied, using default secrets file" $SECRET_VARS_FILE
+fi
+
+if [ $# -gt 3 ]
+  then
+    echo "ERROR: Only 2 or 3 arguments expected, syntax: $BASENAME environment domain [secret-vars-file]"
     exit 1
 fi
 # ----- End Input handing
 
-if [ $# -eq 1 ]
+if [ $# -eq 3 ]
   then
-    SECRET_VARS_FILE=$1
-    echo "INFO: Using file " $SECRET_VARS_FILE " for containing the secrets. Note you must pass this file into you env as well!"
-fi 
+    SECRET_VARS_FILE=$3
+    echo "INFO: Using file " $SECRET_VARS_FILE " for containing the secrets."
+fi
+
+oc_env=$1
+oc_basedomain=$2
 
 set -e
 #set -x
@@ -58,7 +70,19 @@ do
 
   key=$(printf "%s" "$line" | cut -f1 -d:)  
   value=$(echo $line | cut -f2 -d: | xargs)
-  
+
+  if [ "$key" == 'env' ]; then
+    line="env: $oc_env"
+    echo "$line" >> $SV_FILE
+    continue
+  fi
+
+  if [ "$key" == 'base_domain' ]; then
+    line="base_domain: \"{{ env }}.$oc_basedomain\""
+    echo "$line" >> $SV_FILE
+    continue
+  fi
+
   if [ "$value" == 'sha' ]; then
     # sha-key must be later in template file
     # lookup password for the non-sha variant (engine_ldap_password for engine_ldap_password_sha)
