Updated secrets to allow for entering secrets file using command line

diff --git a/scripts/generate-new-passwords b/scripts/generate-new-passwords
--- a/scripts/generate-new-passwords
+++ b/scripts/generate-new-passwords
@@ -10,8 +10,26 @@
 
 SECRET_VARS_FILE=../secrets/secret-vars.yml
 SECRET_VARS_TEMPLATE_FILE=../secrets/secret-vars-template.yml
-
 # ----- End configuration
+
+# ----- Input handling
+if [ $# -eq 0 ]
+  then
+    echo "INFO: No arguments supplied, using default file location" $SECRET_VARS_FILE
+fi
+
+if [ $# -gt 1 ]
+  then
+    echo "ERROR: Only 1 argument expected please supply only the file containing the secrets, for example " $SECRET_VARS_FILE
+    exit 1
+fi
+# ----- End Input handing
+
+if [ $# -eq 1 ]
+  then
+    SECRET_VARS_FILE=$1
+    echo "INFO: Using file " $SECRET_VARS_FILE " for containing the secrets. Note you must pass this file into you env as well!"
+fi 
 
 set -e
 #set -x
